variables:
  TF_VAR_nutanix_username: ${NUTANIX_USERNAME}
  TF_VAR_nutanix_password: ${NUTANIX_PASSWORD}
  TF_PLUGIN_CACHE_DIR: "/opt/infrastructure/terraform-providers"
  # Skip provider verification
  TF_SKIP_PROVIDER_VERIFICATION: "1"


default:
  tags:
    - tf 
    - shell

stages:
  - prepare
  - plan
  - apply

prepare:
  stage: prepare
  script:
    # Create directory structure first
    - mkdir -p terraform/vms
    - mkdir -p terraform/tfvars
    # set symlink for providers
    - ln -s /opt/infrastructure/terraform-providers terraform/.terraform
    # versions needed
    - cp /opt/infrastructure/linux/provisioning/terraform/.terraform.lock.hcl terraform/

    # Create necessary Terraform files from pipeline variables
    - echo "$TERRAFORM_CONTENT" > terraform/vms/lan_vms.tf
    - echo "$TF_MAIN" > terraform/main.tf
    - cat terraform/vms/lan_vms.tf
    - echo "$TF_VARS" > terraform/variables.tf
    - echo "$TF_VARS_LAN_SUBNETS" > terraform/lan_subnets.tfvars
    - echo "$TF_VARS_STORAGE" > terraform/storage_containers.tfvars
    - |
      cat > terraform/terraform.tfvars << EOF
      nutanix_username = "${NUTANIX_USERNAME}"
      nutanix_password = "${NUTANIX_PASSWORD}"
      EOF    

plan:
  stage: plan
  script:
    - cd terraform
    - terraform init --plugin-dir=/opt/infrastructure/terraform-providers
    - terraform plan -var-file="lan_subnets.tfvars" -var-file="storage_containers.tfvars" --out=tfplan
  artifacts:
    paths:
      - terraform/tfplan
    expire_in: 1 week

apply:
  stage: apply
  script:
    - terraform apply -auto-approve tfplan
  when: manual  # Requires manual approval
  dependencies:
    - plan 
